name: Platform Tests & Build
on: [push]

jobs:
  platform_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.19]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install bc
      if: ${{ runner.os == 'Linux' }}

    - name: Tests
      run: go test -tags ci ./...

    - name: Wayland Tests
      run: go test -tags ci,wayland ./...
      if: ${{ runner.os == 'Linux' }}

    - name: Update coverage
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        set -e
        go test -tags ci -covermode=atomic -coverprofile=coverage.out ./...
        coverage=`go tool cover -func coverage.out | grep total | tr -s '\t' | cut -f 3 | grep -o '[^%]*'`
        if (( $(echo "$coverage < 10" | bc) )); then echo "Test coverage lowered"; echo "exit 1"; fi
      if: ${{ runner.os == 'Linux' }}

    - name: Update PR Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: coverage.out
      if: ${{ runner.os == 'Linux' && matrix.go-version == '1.19' }}

    - name: Build Windows binary
      env:
        GOOS: windows
        GOARCH: amd64
      working-directory: .
      run: go build -o filelistbuilder.exe
      if: ${{runner.os == 'Windows'}}

    - name: Build Linux binary
      env:
        GOOS: linux
        GOARCH: amd64
      working-directory: .
      run: go build -o filelistbuilder-linux
      if: ${{runner.os == 'Linux'}}

    - name: Build Darwin binary
      env:
        GOOS: darwin
        GOARCH: amd64
      working-directory: .
      run: go build -o filelistbuilder-darwin
      if: ${{runner.os == 'Darwin'}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Build"
        files: |
          filelistbuilder.exe
      if: ${{runner.os == 'Windows'}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Build"
        files: |
          filelistbuilder-linux
      if: ${{runner.os == 'Linux'}}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Build"
        files: |
          filelistbuilder-darwin
      if: ${{runner.os == 'Darwin'}}      
